# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProvaSicredi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProvaSicredi

	  
  	# TextField/Area pods
		pod 'MaterialComponents/TextControls+FilledTextFields'

	# CleanCode Assistant
		pod 'SwiftLint'


  target 'ProvaSicrediTests' do
    inherit! :search_paths
    # Pods for testing


  end

  target 'ProvaSicrediUITests' do
    # Pods for testing
  end

end
